Feature/error/30
JessyBros/P7_Symfony_BileMo pull request #32
Opened 2021-02-13 13:13 UTC by SiProdZz

Return error in json format 

1 - update route id -> only number is accepted or route not found
2- In list phones and users, if once doesn't exist return error.

2021-02-14 08:23 UTC, crazymad requested changes
404, 403, 500
Validation with Validator

Listener or Subscriber

All responses in JSON

2021-02-14 08:23 UTC, crazymad commented on src/Controller/PhoneController.php
> +        if (!$phoneRepository->findAll()) {
refactor

2021-02-14 08:23 UTC, crazymad commented on src/Controller/UserController.php
> +        if ($userRepository->findBy(["customer" => $customer])) {
refactor

2021-02-15 18:32 UTC, closed without merging

2021-02-15 18:32 UTC, SiProdZz commented
Close this pull request.
Too early to manage errors. Do this at the end